// <auto-generated />
using Catalog.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211009141952_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Description for product 1",
                            Name = "Product 1",
                            Price = 685m
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Description for product 2",
                            Name = "Product 2",
                            Price = 329m
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Description for product 3",
                            Name = "Product 3",
                            Price = 761m
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Description for product 4",
                            Name = "Product 4",
                            Price = 221m
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "Description for product 5",
                            Name = "Product 5",
                            Price = 206m
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "Description for product 6",
                            Name = "Product 6",
                            Price = 391m
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "Description for product 7",
                            Name = "Product 7",
                            Price = 600m
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "Description for product 8",
                            Name = "Product 8",
                            Price = 377m
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "Description for product 9",
                            Name = "Product 9",
                            Price = 497m
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "Description for product 10",
                            Name = "Product 10",
                            Price = 161m
                        },
                        new
                        {
                            ProductId = 11,
                            Description = "Description for product 11",
                            Name = "Product 11",
                            Price = 139m
                        },
                        new
                        {
                            ProductId = 12,
                            Description = "Description for product 12",
                            Name = "Product 12",
                            Price = 690m
                        },
                        new
                        {
                            ProductId = 13,
                            Description = "Description for product 13",
                            Name = "Product 13",
                            Price = 110m
                        },
                        new
                        {
                            ProductId = 14,
                            Description = "Description for product 14",
                            Name = "Product 14",
                            Price = 484m
                        },
                        new
                        {
                            ProductId = 15,
                            Description = "Description for product 15",
                            Name = "Product 15",
                            Price = 235m
                        },
                        new
                        {
                            ProductId = 16,
                            Description = "Description for product 16",
                            Name = "Product 16",
                            Price = 956m
                        },
                        new
                        {
                            ProductId = 17,
                            Description = "Description for product 17",
                            Name = "Product 17",
                            Price = 864m
                        },
                        new
                        {
                            ProductId = 18,
                            Description = "Description for product 18",
                            Name = "Product 18",
                            Price = 458m
                        },
                        new
                        {
                            ProductId = 19,
                            Description = "Description for product 19",
                            Name = "Product 19",
                            Price = 609m
                        },
                        new
                        {
                            ProductId = 20,
                            Description = "Description for product 20",
                            Name = "Product 20",
                            Price = 312m
                        },
                        new
                        {
                            ProductId = 21,
                            Description = "Description for product 21",
                            Name = "Product 21",
                            Price = 399m
                        },
                        new
                        {
                            ProductId = 22,
                            Description = "Description for product 22",
                            Name = "Product 22",
                            Price = 900m
                        },
                        new
                        {
                            ProductId = 23,
                            Description = "Description for product 23",
                            Name = "Product 23",
                            Price = 781m
                        },
                        new
                        {
                            ProductId = 24,
                            Description = "Description for product 24",
                            Name = "Product 24",
                            Price = 252m
                        },
                        new
                        {
                            ProductId = 25,
                            Description = "Description for product 25",
                            Name = "Product 25",
                            Price = 526m
                        },
                        new
                        {
                            ProductId = 26,
                            Description = "Description for product 26",
                            Name = "Product 26",
                            Price = 365m
                        },
                        new
                        {
                            ProductId = 27,
                            Description = "Description for product 27",
                            Name = "Product 27",
                            Price = 197m
                        },
                        new
                        {
                            ProductId = 28,
                            Description = "Description for product 28",
                            Name = "Product 28",
                            Price = 531m
                        },
                        new
                        {
                            ProductId = 29,
                            Description = "Description for product 29",
                            Name = "Product 29",
                            Price = 976m
                        },
                        new
                        {
                            ProductId = 30,
                            Description = "Description for product 30",
                            Name = "Product 30",
                            Price = 513m
                        },
                        new
                        {
                            ProductId = 31,
                            Description = "Description for product 31",
                            Name = "Product 31",
                            Price = 734m
                        },
                        new
                        {
                            ProductId = 32,
                            Description = "Description for product 32",
                            Name = "Product 32",
                            Price = 805m
                        },
                        new
                        {
                            ProductId = 33,
                            Description = "Description for product 33",
                            Name = "Product 33",
                            Price = 336m
                        },
                        new
                        {
                            ProductId = 34,
                            Description = "Description for product 34",
                            Name = "Product 34",
                            Price = 231m
                        },
                        new
                        {
                            ProductId = 35,
                            Description = "Description for product 35",
                            Name = "Product 35",
                            Price = 427m
                        },
                        new
                        {
                            ProductId = 36,
                            Description = "Description for product 36",
                            Name = "Product 36",
                            Price = 466m
                        },
                        new
                        {
                            ProductId = 37,
                            Description = "Description for product 37",
                            Name = "Product 37",
                            Price = 890m
                        },
                        new
                        {
                            ProductId = 38,
                            Description = "Description for product 38",
                            Name = "Product 38",
                            Price = 898m
                        },
                        new
                        {
                            ProductId = 39,
                            Description = "Description for product 39",
                            Name = "Product 39",
                            Price = 727m
                        },
                        new
                        {
                            ProductId = 40,
                            Description = "Description for product 40",
                            Name = "Product 40",
                            Price = 639m
                        },
                        new
                        {
                            ProductId = 41,
                            Description = "Description for product 41",
                            Name = "Product 41",
                            Price = 495m
                        },
                        new
                        {
                            ProductId = 42,
                            Description = "Description for product 42",
                            Name = "Product 42",
                            Price = 425m
                        },
                        new
                        {
                            ProductId = 43,
                            Description = "Description for product 43",
                            Name = "Product 43",
                            Price = 995m
                        },
                        new
                        {
                            ProductId = 44,
                            Description = "Description for product 44",
                            Name = "Product 44",
                            Price = 694m
                        },
                        new
                        {
                            ProductId = 45,
                            Description = "Description for product 45",
                            Name = "Product 45",
                            Price = 682m
                        },
                        new
                        {
                            ProductId = 46,
                            Description = "Description for product 46",
                            Name = "Product 46",
                            Price = 733m
                        },
                        new
                        {
                            ProductId = 47,
                            Description = "Description for product 47",
                            Name = "Product 47",
                            Price = 751m
                        },
                        new
                        {
                            ProductId = 48,
                            Description = "Description for product 48",
                            Name = "Product 48",
                            Price = 246m
                        },
                        new
                        {
                            ProductId = 49,
                            Description = "Description for product 49",
                            Name = "Product 49",
                            Price = 592m
                        },
                        new
                        {
                            ProductId = 50,
                            Description = "Description for product 50",
                            Name = "Product 50",
                            Price = 709m
                        },
                        new
                        {
                            ProductId = 51,
                            Description = "Description for product 51",
                            Name = "Product 51",
                            Price = 556m
                        },
                        new
                        {
                            ProductId = 52,
                            Description = "Description for product 52",
                            Name = "Product 52",
                            Price = 319m
                        },
                        new
                        {
                            ProductId = 53,
                            Description = "Description for product 53",
                            Name = "Product 53",
                            Price = 648m
                        },
                        new
                        {
                            ProductId = 54,
                            Description = "Description for product 54",
                            Name = "Product 54",
                            Price = 469m
                        },
                        new
                        {
                            ProductId = 55,
                            Description = "Description for product 55",
                            Name = "Product 55",
                            Price = 723m
                        },
                        new
                        {
                            ProductId = 56,
                            Description = "Description for product 56",
                            Name = "Product 56",
                            Price = 785m
                        },
                        new
                        {
                            ProductId = 57,
                            Description = "Description for product 57",
                            Name = "Product 57",
                            Price = 548m
                        },
                        new
                        {
                            ProductId = 58,
                            Description = "Description for product 58",
                            Name = "Product 58",
                            Price = 608m
                        },
                        new
                        {
                            ProductId = 59,
                            Description = "Description for product 59",
                            Name = "Product 59",
                            Price = 694m
                        },
                        new
                        {
                            ProductId = 60,
                            Description = "Description for product 60",
                            Name = "Product 60",
                            Price = 841m
                        },
                        new
                        {
                            ProductId = 61,
                            Description = "Description for product 61",
                            Name = "Product 61",
                            Price = 294m
                        },
                        new
                        {
                            ProductId = 62,
                            Description = "Description for product 62",
                            Name = "Product 62",
                            Price = 169m
                        },
                        new
                        {
                            ProductId = 63,
                            Description = "Description for product 63",
                            Name = "Product 63",
                            Price = 401m
                        },
                        new
                        {
                            ProductId = 64,
                            Description = "Description for product 64",
                            Name = "Product 64",
                            Price = 983m
                        },
                        new
                        {
                            ProductId = 65,
                            Description = "Description for product 65",
                            Name = "Product 65",
                            Price = 426m
                        },
                        new
                        {
                            ProductId = 66,
                            Description = "Description for product 66",
                            Name = "Product 66",
                            Price = 333m
                        },
                        new
                        {
                            ProductId = 67,
                            Description = "Description for product 67",
                            Name = "Product 67",
                            Price = 454m
                        },
                        new
                        {
                            ProductId = 68,
                            Description = "Description for product 68",
                            Name = "Product 68",
                            Price = 878m
                        },
                        new
                        {
                            ProductId = 69,
                            Description = "Description for product 69",
                            Name = "Product 69",
                            Price = 156m
                        },
                        new
                        {
                            ProductId = 70,
                            Description = "Description for product 70",
                            Name = "Product 70",
                            Price = 768m
                        },
                        new
                        {
                            ProductId = 71,
                            Description = "Description for product 71",
                            Name = "Product 71",
                            Price = 165m
                        },
                        new
                        {
                            ProductId = 72,
                            Description = "Description for product 72",
                            Name = "Product 72",
                            Price = 966m
                        },
                        new
                        {
                            ProductId = 73,
                            Description = "Description for product 73",
                            Name = "Product 73",
                            Price = 730m
                        },
                        new
                        {
                            ProductId = 74,
                            Description = "Description for product 74",
                            Name = "Product 74",
                            Price = 970m
                        },
                        new
                        {
                            ProductId = 75,
                            Description = "Description for product 75",
                            Name = "Product 75",
                            Price = 816m
                        },
                        new
                        {
                            ProductId = 76,
                            Description = "Description for product 76",
                            Name = "Product 76",
                            Price = 974m
                        },
                        new
                        {
                            ProductId = 77,
                            Description = "Description for product 77",
                            Name = "Product 77",
                            Price = 904m
                        },
                        new
                        {
                            ProductId = 78,
                            Description = "Description for product 78",
                            Name = "Product 78",
                            Price = 186m
                        },
                        new
                        {
                            ProductId = 79,
                            Description = "Description for product 79",
                            Name = "Product 79",
                            Price = 570m
                        },
                        new
                        {
                            ProductId = 80,
                            Description = "Description for product 80",
                            Name = "Product 80",
                            Price = 793m
                        },
                        new
                        {
                            ProductId = 81,
                            Description = "Description for product 81",
                            Name = "Product 81",
                            Price = 613m
                        },
                        new
                        {
                            ProductId = 82,
                            Description = "Description for product 82",
                            Name = "Product 82",
                            Price = 950m
                        },
                        new
                        {
                            ProductId = 83,
                            Description = "Description for product 83",
                            Name = "Product 83",
                            Price = 939m
                        },
                        new
                        {
                            ProductId = 84,
                            Description = "Description for product 84",
                            Name = "Product 84",
                            Price = 367m
                        },
                        new
                        {
                            ProductId = 85,
                            Description = "Description for product 85",
                            Name = "Product 85",
                            Price = 956m
                        },
                        new
                        {
                            ProductId = 86,
                            Description = "Description for product 86",
                            Name = "Product 86",
                            Price = 514m
                        },
                        new
                        {
                            ProductId = 87,
                            Description = "Description for product 87",
                            Name = "Product 87",
                            Price = 256m
                        },
                        new
                        {
                            ProductId = 88,
                            Description = "Description for product 88",
                            Name = "Product 88",
                            Price = 867m
                        },
                        new
                        {
                            ProductId = 89,
                            Description = "Description for product 89",
                            Name = "Product 89",
                            Price = 508m
                        },
                        new
                        {
                            ProductId = 90,
                            Description = "Description for product 90",
                            Name = "Product 90",
                            Price = 642m
                        },
                        new
                        {
                            ProductId = 91,
                            Description = "Description for product 91",
                            Name = "Product 91",
                            Price = 918m
                        },
                        new
                        {
                            ProductId = 92,
                            Description = "Description for product 92",
                            Name = "Product 92",
                            Price = 382m
                        },
                        new
                        {
                            ProductId = 93,
                            Description = "Description for product 93",
                            Name = "Product 93",
                            Price = 303m
                        },
                        new
                        {
                            ProductId = 94,
                            Description = "Description for product 94",
                            Name = "Product 94",
                            Price = 886m
                        },
                        new
                        {
                            ProductId = 95,
                            Description = "Description for product 95",
                            Name = "Product 95",
                            Price = 445m
                        },
                        new
                        {
                            ProductId = 96,
                            Description = "Description for product 96",
                            Name = "Product 96",
                            Price = 426m
                        },
                        new
                        {
                            ProductId = 97,
                            Description = "Description for product 97",
                            Name = "Product 97",
                            Price = 123m
                        },
                        new
                        {
                            ProductId = 98,
                            Description = "Description for product 98",
                            Name = "Product 98",
                            Price = 112m
                        },
                        new
                        {
                            ProductId = 99,
                            Description = "Description for product 99",
                            Name = "Product 99",
                            Price = 367m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.Property<int>("ProductInStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductInStockId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductInStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
